import type { PassportPresentationResponse, PassportSectionAvailability, PassportSectionKey, PlayerIdentityPresentation, PresentationAvailability } from '../passport-types';
export type SectionAvailabilityProjection = Readonly<{ key: PassportSectionKey; availability: PassportSectionAvailability; message: string | null }>;
export type AcademyOriginProjection = Readonly<{ kind: 'available'; name: string }> | Readonly<{ kind: 'unavailable'; label: string }>;
export type PhotographProjection = Readonly<{ kind: 'neutral-placeholder'; label: string }>;
const SECTION_MAP = { resumen: 'SUMMARY', estadisticas: 'STATISTICS', partidos: 'MATCHES', videos: 'VIDEOS' } as const;
const MESSAGE: Readonly<Record<PassportSectionAvailability, string>> = Object.freeze({ available: 'Información disponible', empty: 'No hay información para esta sección.', unavailable: 'Esta sección no está disponible.', restricted: 'No tienes autorización para ver esta sección.' });
export function toSectionAvailability(value: PresentationAvailability | undefined): PassportSectionAvailability { if (value === 'AVAILABLE') return 'available'; if (value === 'EMPTY') return 'empty'; if (value === 'RESTRICTED') return 'restricted'; return 'unavailable'; }
export function getSectionAvailability(presentation: PassportPresentationResponse | null, key: PassportSectionKey): PassportSectionAvailability { return toSectionAvailability(presentation?.sections.find(section => section.section === SECTION_MAP[key])?.availability); }
export function projectSectionAvailability(presentation: PassportPresentationResponse | null, key: PassportSectionKey): SectionAvailabilityProjection { const availability = getSectionAvailability(presentation, key); return Object.freeze({ key, availability, message: availability === 'available' ? null : MESSAGE[availability] }); }
export function toPlayerIdentity(identity: PassportPresentationResponse['identity'] | null | undefined): PlayerIdentityPresentation | null { if (!identity) return null; const value = (field: { availability: PresentationAvailability; value?: string | null }) => field.availability === 'AVAILABLE' ? field.value ?? null : null; return { displayName: identity.displayName, position: value(identity.primaryPosition), ageCategory: value(identity.declaredAgeCategory), city: value(identity.city), country: value(identity.country), dominantFoot: value(identity.dominantFoot), academyOriginName: value(identity.academyOrigin), photographPlaceholder: 'neutral-placeholder' }; }
export function projectAcademyOrigin(player: PlayerIdentityPresentation | null): AcademyOriginProjection { const name = player?.academyOriginName?.trim(); return name ? Object.freeze({ kind: 'available' as const, name }) : Object.freeze({ kind: 'unavailable' as const, label: 'Academia no disponible' }); }
export function projectPhotographPlaceholder(): PhotographProjection { return Object.freeze({ kind: 'neutral-placeholder' as const, label: 'Fotografía no disponible' }); }
