import { Pressable, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';

import { LiquidGlassPanel } from '../../design/components/liquid-glass-panel';
import { authTokens } from '../../design/tokens';
import type { DossierFilters, DossierSummary } from '../administrator-api';
import type { DossierViewState } from './admin-dossiers-state';

const statusLabels = { CONFIRMED: 'Confirmado', DELETION_PENDING: 'Eliminación pendiente', RECOVERY_REQUIRED: 'Requiere recuperación', APPROVED: 'Aprobado' } as const;
export function AdminDossiersList({ filters, items, state, page, canGoPrevious, canGoNext, onFilters, onRetry, onOpen, onNext, onPrevious, onScroll, previewMode }: Readonly<{
  filters: DossierFilters; items: readonly DossierSummary[]; state: DossierViewState; page: number; canGoPrevious: boolean; canGoNext: boolean;
  onFilters: (filters: DossierFilters) => void; onRetry: () => void; onOpen: (id: string) => void; onNext: () => void; onPrevious: () => void; onScroll: (offset: number) => void; previewMode?: 'desktop' | 'mobile';
}>) {
  const dimensions = useWindowDimensions(); const desktop = previewMode ? previewMode === 'desktop' : dimensions.width >= authTokens.breakpoints.desktop;
  const body = state === 'ready' ? <View style={styles.cards}>{items.map((item) => <DossierCard key={item.dossierId} item={item} desktop={desktop} onOpen={onOpen} />)}</View> : <StatePanel state={state} onRetry={onRetry} />;
  return <ScrollView accessibilityLabel="Lista de expedientes" onScroll={(event) => onScroll(event.nativeEvent.contentOffset.y)} scrollEventThrottle={100} contentContainerStyle={[styles.page, !desktop && styles.pageMobile]}>
    <View style={[styles.header, !desktop && styles.headerMobile]}><View><Text accessibilityRole="header" style={[styles.title, !desktop && styles.titleMobile]}>Expedientes</Text><Text style={styles.subtitle}>Consulta de expedientes confirmados</Text></View><Text style={styles.info}>ⓘ Solo consulta · Sin acciones de aprobación</Text></View>
    <LiquidGlassPanel style={[styles.filters, !desktop && styles.filtersMobile]}>
      <TextInput accessibilityLabel="Buscar expedientes" placeholder="Buscar expediente, solicitud o pasaporte" placeholderTextColor="#91a99b" value={filters.query ?? ''} onChangeText={(query) => onFilters({ ...filters, ...(query ? { query } : { query: undefined }) })} style={styles.search} />
      <View style={styles.filterRow}><Filter label={filters.status ? statusLabels[filters.status] : 'Estado'} onPress={() => onFilters({ ...filters, status: filters.status ? undefined : 'APPROVED' })} /><Filter label={filters.requestType ? 'Tipo aplicado' : 'Tipo de origen'} onPress={() => onFilters({ ...filters, requestType: filters.requestType ? undefined : 'PERSONAL_ADULT' })} /><Filter label={filters.confirmedFrom ? 'Fecha aplicada' : 'Fecha de confirmación'} onPress={() => onFilters({ ...filters, confirmedFrom: filters.confirmedFrom ? undefined : '2026-09-01' })} /></View>
    </LiquidGlassPanel>
    {body}
    {state === 'ready' ? <View style={styles.pagination}><Text style={styles.pageCopy}>Página {page + 1} · {items.length} expedientes</Text><View style={styles.pageButtons}><PageButton label="Anterior" disabled={!canGoPrevious} onPress={onPrevious} /><PageButton label={desktop ? 'Siguiente' : 'Cargar más'} disabled={!canGoNext} onPress={onNext} /></View></View> : null}
  </ScrollView>;
}

function DossierCard({ item, desktop, onOpen }: Readonly<{ item: DossierSummary; desktop: boolean; onOpen: (id: string) => void }>) {
  return <Pressable accessibilityRole="button" accessibilityLabel="Abrir expediente" onPress={() => onOpen(item.dossierId)}>
    <LiquidGlassPanel style={[styles.card, desktop && styles.cardDesktop]}><View style={styles.identity}><Text style={styles.folder}>□</Text><View style={styles.identityCopy}><Text style={styles.label}>{item.dossierName ?? 'Expediente'}</Text><Text style={styles.personLabel}>Nombre del expediente: {item.dossierName ?? 'Sin nombre registrado'}</Text><Text style={styles.personLabel}>Jugador: {item.displayLabel}</Text></View></View><Text style={[styles.badge, item.status === 'RECOVERY_REQUIRED' && styles.badgeWarning]}>{statusLabels[item.status]}</Text><Text style={styles.date}>{new Date(item.confirmedAt).toLocaleDateString('es-CO', { day: 'numeric', month: 'short', year: 'numeric' })}</Text><View style={styles.linkColumn}><Text style={styles.linkLabel}>Solicitud</Text></View><View style={styles.linkColumn}><Text style={styles.linkLabel}>Pasaporte</Text><Text style={styles.linkName}>{'notApplicable' in item.linkedPassport ? 'No aplica' : 'Vinculado'}</Text></View><Text style={styles.chevron}>›</Text></LiquidGlassPanel>
  </Pressable>;
}
function Filter({ label, onPress }: Readonly<{ label: string; onPress: () => void }>) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={styles.filter}><Text style={styles.filterText}>{label}⌄</Text></Pressable>; }
function PageButton({ label, disabled, onPress }: Readonly<{ label: string; disabled: boolean; onPress: () => void }>) { return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={[styles.pageButton, disabled && styles.disabled]}><Text style={styles.pageButtonText}>{label}</Text></Pressable>; }
function StatePanel({ state, onRetry }: Readonly<{ state: DossierViewState; onRetry: () => void }>) {
  const copy = state === 'loading' ? 'Cargando expedientes…' : state === 'empty' ? 'Aún no hay expedientes confirmados.' : state === 'no-results' ? 'No hay expedientes que coincidan con los filtros.' : state === 'restricted' ? 'No tienes acceso a Expedientes.' : state === 'unavailable' ? 'Expedientes no está disponible en este momento.' : 'No pudimos cargar Expedientes.';
  return <LiquidGlassPanel style={styles.state}><Text accessibilityRole="alert" style={styles.stateText}>{copy}</Text>{state === 'unavailable' || state === 'error' ? <PageButton label="Reintentar" disabled={false} onPress={onRetry} /> : null}</LiquidGlassPanel>;
}
const styles = StyleSheet.create({
  linkName: { color: '#f7f8f2', fontSize: 12, fontWeight: '800', flexShrink: 1 },
  identityCopy: { flexShrink: 1 },
  personLabel: { color: '#b9c9bf', fontSize: 12, marginTop: 3 },
  page: { alignSelf: 'center', gap: 14, maxWidth: 1160, padding: 28, paddingBottom: 50, width: '100%' }, pageMobile: { padding: 14, paddingBottom: 30 }, header: { alignItems: 'flex-end', flexDirection: 'row', justifyContent: 'space-between' }, headerMobile: { alignItems: 'flex-start', flexDirection: 'column', gap: 8 }, title: { color: '#f7f8f2', fontSize: 48, fontWeight: '900' }, titleMobile: { fontSize: 34 }, subtitle: { color: '#c6d2cb', fontSize: 19 }, info: { color: '#b9c9bf', fontSize: 12 }, filters: { gap: 12, padding: 14 }, filtersMobile: { gap: 9 }, search: { borderColor: '#d6ff19', borderRadius: 8, borderWidth: 2, color: '#f7f8f2', minHeight: 48, paddingHorizontal: 14 }, filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, filter: { borderColor: 'rgba(225,255,235,.55)', borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 44, paddingHorizontal: 14 }, filterText: { color: '#f4f6f1' }, cards: { gap: 8 }, card: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: 12, minHeight: 96, padding: 14 }, cardDesktop: { minHeight: 76 }, identity: { alignItems: 'center', flexDirection: 'row', gap: 10, minWidth: 250 }, folder: { borderColor: '#d8efe0', borderRadius: 20, borderWidth: 1, color: '#f6f8f3', fontSize: 24, padding: 5 }, reference: { color: '#aebfb5', fontSize: 11, marginTop: 3 }, label: { color: '#f7f8f2', fontSize: 15, fontWeight: '900' }, badge: { borderColor: '#d6ff19', borderRadius: 14, borderWidth: 1, color: '#d6ff19', minWidth: 110, paddingHorizontal: 10, paddingVertical: 5, textAlign: 'center' }, badgeWarning: { borderColor: '#ffb96a', color: '#ffb96a' }, date: { color: '#dce8df', minWidth: 105 }, linkColumn: { minWidth: 155 }, linkLabel: { color: '#eef4ef', fontSize: 12, fontWeight: '700' }, linkValue: { color: '#96a99d', fontSize: 10, marginTop: 3 }, chevron: { color: '#d6ff19', fontSize: 28, marginLeft: 'auto' }, pagination: { alignItems: 'center', borderTopColor: 'rgba(210,255,226,.3)', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', paddingTop: 12 }, pageCopy: { color: '#dce8df' }, pageButtons: { flexDirection: 'row', gap: 8 }, pageButton: { alignItems: 'center', borderColor: '#cde6d6', borderRadius: 8, borderWidth: 1, justifyContent: 'center', minHeight: 44, minWidth: 100, paddingHorizontal: 14 }, pageButtonText: { color: '#f5f7ef', fontWeight: '800' }, disabled: { opacity: .35 }, state: { alignItems: 'center', gap: 14, minHeight: 240, justifyContent: 'center', padding: 28 }, stateText: { color: '#eef4ef', fontSize: 17, textAlign: 'center' },
});
