ALTER TYPE "RegistrationEvidenceCategory" RENAME VALUE 'CIVIL_IDENTITY' TO 'MINOR_CIVIL_IDENTITY';
ALTER TYPE "RegistrationEvidenceCategory" RENAME VALUE 'RESPONSIBLE_AUTHORIZATION' TO 'RESPONSIBLE_AUTHORITY';
ALTER TYPE "RegistrationEvidenceCategory" ADD VALUE IF NOT EXISTS 'ACADEMY_ACCOUNT_AUTHORIZATION';
