import { createPassportApi, PASSPORT_OPERATION_PATHS } from './passport-api';
import type { CreateDraftInput, PassportPresentationResponse, PassportSummaryResponse } from './passport-types';
const response = (status: number, body?: unknown) => new Response(body === undefined ? undefined : JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
const summary: PassportSummaryResponse = { passportId: '44444444-4444-4444-8444-444444444444', displayName: 'Nombre Autorizado', lifecycleState: 'DRAFT', origin: 'PARTICULAR', academyOriginName: null, availableActions: ['EDIT', 'SUBMIT', 'VIEW_HISTORY'] };
const presentation: PassportPresentationResponse = { passportId: summary.passportId, lifecycleState: 'DRAFT', identity: { displayName: 'Nombre Autorizado', primaryPosition: { availability: 'AVAILABLE', value: 'Delantero' }, declaredAgeCategory: { availability: 'AVAILABLE', value: 'Sub-15' }, city: { availability: 'AVAILABLE', value: 'Medellín' }, country: { availability: 'AVAILABLE', value: 'Colombia' }, dominantFoot: { availability: 'AVAILABLE', value: 'Izquierda' }, academyOrigin: { availability: 'UNAVAILABLE', value: null }, photograph: { state: 'NEUTRAL_LOCAL_PLACEHOLDER' } }, sections: [{ section: 'SUMMARY', availability: 'AVAILABLE', dependency: null }, { section: 'STATISTICS', availability: 'FUTURE_DEPENDENCY', dependency: 'STATISTICS_FEM' }, { section: 'MATCHES', availability: 'FUTURE_DEPENDENCY', dependency: 'MATCHES' }, { section: 'VIDEOS', availability: 'FUTURE_DEPENDENCY', dependency: 'AUDIOVISUAL' }] };
const draft: CreateDraftInput = { managementContext: 'SELF', playerLegalName: 'Nombre De Prueba', dateOfBirth: '1990-05-04', playerDocument: { documentType: 'CC', documentNumber: 'ABC-123' }, footballProfile: { primaryPosition: 'Delantero', declaredAgeCategory: 'Mayores', city: 'Medellín', country: 'Colombia', dominantFoot: 'LEFT' } };
describe('Feature 005 corrective passport API boundary', () => {
  it('exposes the finalized operations including private draft, confirmation and separate internal history', () => { expect(PASSPORT_OPERATION_PATHS).toMatchObject({ representationConfirmation: '/passport-representation-confirmations', editableDraft: '/passports/:passportId/draft', internalHistory: '/passports/:passportId/internal-history' }); expect(Object.values(PASSPORT_OPERATION_PATHS)).not.toEqual(expect.arrayContaining([expect.stringMatching(/public|search|upload|photo/i)])); });
  it('sends explicit list context and maps finalized presentation without decoding JWT material', async () => { const fetcher = jest.fn().mockResolvedValueOnce(response(200, { context: 'PARTICULAR', passports: [summary], collectionActions: ['VIEW_PARTICULAR_SELECTOR'] })).mockResolvedValueOnce(response(200, presentation)); const api = createPassportApi({ apiBaseUrl: 'https://api.example.test/base/' }, fetcher); await expect(api.list({ context: 'PARTICULAR' }, 'token')).resolves.toEqual({ kind: 'success', value: { context: 'PARTICULAR', passports: [summary], collectionActions: ['VIEW_PARTICULAR_SELECTOR'] } }); await expect(api.presentation(summary.passportId, 'token')).resolves.toEqual({ kind: 'success', value: presentation }); expect(fetcher.mock.calls[0][0]).toBe('https://api.example.test/passports?context=PARTICULAR'); expect(fetcher.mock.calls[0][1].headers.Authorization).toBe('Bearer token'); });
  it('serializes the nested SELF draft and never adds isAdult', async () => { const fetcher = jest.fn().mockResolvedValue(response(201, { ...summary, version: 1, correctionReason: null, ageSensitiveMutationAvailability: 'AVAILABLE' })); const api = createPassportApi({ apiBaseUrl: 'https://api.example.test' }, fetcher); await api.createDraft(draft, 'token'); const sent = JSON.parse(fetcher.mock.calls[0][1].body); expect(sent).toEqual(draft); expect(sent).not.toHaveProperty('isAdult'); });
  it('maps safe errors from code without retaining response details', async () => { const fetcher = jest.fn().mockResolvedValueOnce(response(409, { code: 'duplicate_passport', message: 'Conflict' })).mockResolvedValueOnce(response(404, { code: 'passport_not_found', diagnostic: 'secret' })).mockRejectedValueOnce(new Error('offline')); const api = createPassportApi({ apiBaseUrl: 'https://api.example.test' }, fetcher); await expect(api.createDraft(draft, 'token')).resolves.toEqual({ kind: 'duplicate-passport' }); await expect(api.status(summary.passportId, 'token')).resolves.toEqual({ kind: 'not-found-safe' }); await expect(api.list({ context: 'PARTICULAR' }, 'token')).resolves.toEqual({ kind: 'connectivity-failure' }); });
});
