import { PassportStateMachine } from './passport-state';
import type { PassportApi } from './passport-api';
import type { CreateDraftInput, PassportPresentationResponse, PassportStatusResponse } from './passport-types';
type MockApi = { [K in keyof PassportApi]: jest.Mock };
const passportId = '44444444-4444-4444-8444-444444444444';
const status: PassportStatusResponse = { passportId, displayName: 'Nombre Autorizado', lifecycleState: 'DRAFT', origin: 'PARTICULAR', academyOriginName: null, availableActions: ['VIEW', 'EDIT', 'SUBMIT', 'VIEW_HISTORY'], version: 2, correctionReason: null, ageSensitiveMutationAvailability: 'AVAILABLE' };
const presentation: PassportPresentationResponse = { passportId, lifecycleState: 'DRAFT', identity: { displayName: 'Nombre Autorizado', primaryPosition: { availability: 'AVAILABLE', value: 'Delantero' }, declaredAgeCategory: { availability: 'AVAILABLE', value: 'Sub-15' }, city: { availability: 'AVAILABLE', value: 'Medellín' }, country: { availability: 'AVAILABLE', value: 'Colombia' }, dominantFoot: { availability: 'AVAILABLE', value: 'Izquierda' }, academyOrigin: { availability: 'UNAVAILABLE', value: null }, photograph: { state: 'NEUTRAL_LOCAL_PLACEHOLDER' } }, sections: [] };
const draft: CreateDraftInput = { managementContext: 'SELF', playerLegalName: 'Privado', dateOfBirth: '1990-05-04', playerDocument: { documentType: 'CC', documentNumber: '1234567890' }, footballProfile: { primaryPosition: 'Delantero', declaredAgeCategory: 'Mayores', city: 'Medellín', country: 'Colombia', dominantFoot: 'LEFT' } };
function api(overrides: Partial<MockApi> = {}): MockApi { return { createRepresentationConfirmation: jest.fn(), list: jest.fn().mockResolvedValue({ kind: 'success', value: { context: 'PARTICULAR', passports: [], collectionActions: ['CREATE_SELF'] } }), createDraft: jest.fn(), status: jest.fn(), presentation: jest.fn(), editableDraft: jest.fn(), editDraft: jest.fn(), submit: jest.fn(), returnForCorrection: jest.fn(), resolveDuplicate: jest.fn(), approve: jest.fn(), activate: jest.fn(), history: jest.fn(), internalHistory: jest.fn(), ...overrides }; }
describe('Feature 005 corrective passport state', () => {
  it('requires session material and keeps list context explicit', async () => { const mock = api(); const machine = new PassportStateMachine({ api: mock as unknown as PassportApi, getAccessToken: () => null }); await machine.loadList({ context: 'PARTICULAR' }); expect(machine.state.notice).toBe('authentication-failed'); expect(mock.list).not.toHaveBeenCalled(); });
  it('stores backend collection actions and never derives them from roles', async () => { const mock = api(); const machine = new PassportStateMachine({ api: mock as unknown as PassportApi, getAccessToken: () => 'token' }); await machine.loadList({ context: 'PARTICULAR' }); expect(machine.state.collectionActions).toEqual(['CREATE_SELF']); expect(machine.hasCollectionAction('CREATE_SELF')).toBe(true); expect(mock.list).toHaveBeenCalledWith({ context: 'PARTICULAR' }, 'token'); });
  it('selects status and presentation while using only projected actions', async () => { const mock = api({ status: jest.fn().mockResolvedValue({ kind: 'success', value: status }), presentation: jest.fn().mockResolvedValue({ kind: 'success', value: presentation }) }); const machine = new PassportStateMachine({ api: mock as unknown as PassportApi, getAccessToken: () => 'token' }); await machine.selectPassport(passportId); expect(machine.hasCapability('EDIT')).toBe(true); expect(machine.hasCapability('ACTIVATE')).toBe(false); });
  it('passes expected version and permits only one mutation in flight', async () => { let finish!: (value: unknown) => void; const mock = api({ status: jest.fn().mockResolvedValue({ kind: 'success', value: status }), presentation: jest.fn().mockResolvedValue({ kind: 'success', value: presentation }), submit: jest.fn(() => new Promise(resolve => { finish = resolve; })) }); const machine = new PassportStateMachine({ api: mock as unknown as PassportApi, getAccessToken: () => 'token' }); await machine.selectPassport(passportId); const first = machine.submit(passportId); await expect(machine.submit(passportId)).resolves.toEqual({ kind: 'invalid-state' }); expect(mock.submit).toHaveBeenCalledWith(passportId, { expectedVersion: 2 }, 'token'); finish({ kind: 'success', value: status }); await first; });
  it('does not retain submitted private identity or documents in public state', async () => { const mock = api({ createDraft: jest.fn().mockResolvedValue({ kind: 'success', value: status }) }); const machine = new PassportStateMachine({ api: mock as unknown as PassportApi, getAccessToken: () => 'token' }); await machine.loadList({ context: 'PARTICULAR' }); await machine.createDraft(draft); expect(JSON.stringify(machine.state)).not.toContain(draft.playerDocument.documentNumber); expect(JSON.stringify(machine.state)).not.toContain(draft.playerLegalName); });
});
