import { Image, Pressable, ScrollView, StyleSheet, Text, useWindowDimensions, View } from 'react-native';

import { LiquidGlassPanel } from '../../design/components/liquid-glass-panel';
import { authTokens } from '../../design/tokens';
import type { AdministratorDestination } from '../shell/administrator-shell';
import type { AdminHomeView } from './admin-home-state';

export function AdminHome({ view, onNavigate, onRetry, previewMode }: Readonly<{
  view: AdminHomeView;
  onNavigate: (destination: AdministratorDestination) => void;
  onRetry: () => void;
  previewMode?: 'desktop' | 'mobile';
}>) {
  const dimensions = useWindowDimensions(); const desktop = previewMode ? previewMode === 'desktop' : dimensions.width >= authTokens.breakpoints.desktop;
  if (view.state !== 'ready') return <StatePanel state={view.state} onRetry={onRetry} desktop={desktop} />;
  const metrics = [
    { label: 'Solicitudes pendientes', value: view.requestsPending, detail: 'Revisa y decide las solicitudes de registro.', action: 'Revisar solicitudes', destination: 'requests' as const, accent: '#d6ff19', icon: require('../../../assets/passport/icons/file-description.png') },
    { label: 'Expedientes confirmados', value: view.confirmedDossiers, detail: 'Consulta los expedientes confirmados existentes.', action: 'Abrir expedientes', destination: 'dossiers' as const, accent: '#64efb4', icon: require('../../../assets/passport/icons/file-description.png') },
    { label: 'Pasaportes sin Analista', value: view.unassignedPassports, detail: 'Asigna custodia a los pasaportes disponibles.', action: 'Asignar custodia', destination: 'custody' as const, accent: '#ff7a23', icon: require('../../../assets/passport/icons/shield-star.png') },
    { label: 'Pasaportes con Analista', value: view.assignedPassports, detail: 'Consulta la distribución actual de custodias.', action: 'Ver distribución', destination: 'custody' as const, accent: '#bdff35', icon: require('../../../assets/passport/icons/users.png') },
  ];
  return <ScrollView accessibilityLabel="Inicio administrativo" contentContainerStyle={[styles.page, !desktop && styles.pageMobile]}>
    <View><Text accessibilityRole="header" style={[styles.title, !desktop && styles.titleMobile]}>Inicio</Text><Text style={[styles.subtitle, !desktop && styles.subtitleMobile]}>Operación de registro y custodia</Text></View>
    <View testID="administrator-home-metrics" style={[styles.metrics, !desktop && styles.metricsMobile]}>{metrics.map((metric) => <MetricCard key={metric.label} {...metric} desktop={desktop} onNavigate={onNavigate} />)}</View>
    <View style={[styles.lowerGrid, !desktop && styles.lowerGridMobile]}>
      <LiquidGlassPanel style={styles.workload}><Text style={styles.sectionTitle}>Carga por Analista</Text><Text style={styles.sectionSubtitle}>Pasaportes asignados en custodia.</Text><View style={styles.tableHeader}><Text style={styles.tableHeaderText}>ANALISTA</Text><Text style={styles.tableHeaderText}>PASAPORTES ASIGNADOS</Text></View>{view.analysts.map((analyst) => <View key={analyst.identityId} style={styles.analystRow}><View style={styles.analystIdentity}><View style={styles.initials}><Text style={styles.initialsText}>{initials(analyst.displayLabel)}</Text></View><Text style={styles.analystName}>{analyst.displayLabel}</Text></View><Text style={styles.workloadCount}>{analyst.activeCustodyCount} pasaportes</Text><Pressable accessibilityRole="button" accessibilityLabel={`Ver custodia de ${analyst.displayLabel}`} onPress={() => onNavigate('custody')} style={styles.smallButton}><Text style={styles.smallButtonText}>Custodia →</Text></Pressable></View>)}</LiquidGlassPanel>
      <LiquidGlassPanel style={styles.activity}><Text style={styles.sectionTitle}>Actividad prioritaria</Text><Text style={styles.sectionSubtitle}>Acciones recomendadas para continuar con la operación.</Text><Activity label="Revisar solicitudes de registro" detail={`Tienes ${view.requestsPending} solicitudes pendientes de revisión y decisión.`} onPress={() => onNavigate('requests')} /><Activity label="Asignar custodias pendientes" detail={`Hay ${view.unassignedPassports} pasaportes sin Analista.`} onPress={() => onNavigate('custody')} /></LiquidGlassPanel>
    </View>
  </ScrollView>;
}

function MetricCard({ label, value, detail, action, destination, accent, icon, desktop, onNavigate }: Readonly<{ label: string; value: number; detail: string; action: string; destination: AdministratorDestination; accent: string; icon: number; desktop: boolean; onNavigate: (destination: AdministratorDestination) => void }>) {
  return <LiquidGlassPanel style={[styles.metric, desktop ? styles.metricDesktop : styles.metricMobile]}><View style={styles.metricTop}><View style={[styles.metricIcon, { borderColor: accent }]}><Image accessible={false} source={icon} resizeMode="contain" style={[styles.metricIconImage, { tintColor: accent }]} /></View><Text style={[styles.metricValue, { color: accent }]}>{value}</Text></View><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricDetail}>{detail}</Text><Pressable accessibilityRole="button" accessibilityLabel={action} onPress={() => onNavigate(destination)} style={[styles.metricButton, { borderColor: accent }]}><Text style={styles.metricButtonText}>{action}</Text><Text style={[styles.arrow, { color: accent }]}>→</Text></Pressable></LiquidGlassPanel>;
}
function Activity({ label, detail, onPress }: Readonly<{ label: string; detail: string; onPress: () => void }>) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={styles.activityRow}><View><Text style={styles.activityLabel}>{label}</Text><Text style={styles.activityDetail}>{detail}</Text></View><Text style={styles.activityArrow}>›</Text></Pressable>; }
function StatePanel({ state, onRetry, desktop }: Readonly<{ state: Exclude<AdminHomeView['state'], 'ready'>; onRetry: () => void; desktop: boolean }>) { const copy = state === 'loading' ? 'Cargando inicio administrativo…' : state === 'restricted' ? 'No tienes acceso al inicio administrativo.' : state === 'unavailable' ? 'El inicio administrativo no está disponible.' : 'No pudimos cargar el inicio administrativo.'; return <View style={[styles.page, !desktop && styles.pageMobile]}><Text accessibilityRole="header" style={[styles.title, !desktop && styles.titleMobile]}>Inicio</Text><LiquidGlassPanel style={styles.state}><Text accessibilityRole="alert" style={styles.stateCopy}>{copy}</Text>{state === 'unavailable' || state === 'error' ? <Pressable accessibilityRole="button" accessibilityLabel="Reintentar" onPress={onRetry} style={styles.retry}><Text style={styles.retryText}>Reintentar</Text></Pressable> : null}</LiquidGlassPanel></View>; }
function initials(label: string) { return label.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]?.toUpperCase()).join(''); }

const styles = StyleSheet.create({
  page: { alignSelf: 'center', gap: 18, maxWidth: 1160, padding: 34, paddingBottom: 50, width: '100%' }, pageMobile: { gap: 10, padding: 14, paddingBottom: 26 }, title: { color: '#f7f8f2', fontSize: 52, fontWeight: '900', letterSpacing: -1.5 }, titleMobile: { fontSize: 38 }, subtitle: { color: '#c6d2cb', fontSize: 27, marginTop: -5 }, subtitleMobile: { fontSize: 20 },
  metrics: { flexDirection: 'row', gap: 12 }, metricsMobile: { flexWrap: 'wrap', gap: 8 }, metric: { padding: 16 }, metricDesktop: { flex: 1, minHeight: 244 }, metricMobile: { minHeight: 176, width: '48.8%' }, metricTop: { alignItems: 'center', flexDirection: 'row', gap: 12 }, metricIcon: { alignItems: 'center', borderRadius: 25, borderWidth: 1.5, height: 50, justifyContent: 'center', width: 50 }, metricIconImage: { height: 26, width: 26 }, metricValue: { fontSize: 50, fontWeight: '900', lineHeight: 54 }, metricLabel: { color: '#f7f8f2', fontSize: 17, fontWeight: '900', marginTop: 8 }, metricDetail: { color: '#d0d9d3', flex: 1, fontSize: 14, lineHeight: 19, marginTop: 8 }, metricButton: { alignItems: 'center', borderRadius: 9, borderWidth: 1.5, flexDirection: 'row', justifyContent: 'space-between', marginTop: 14, minHeight: 46, paddingHorizontal: 13 }, metricButtonText: { color: '#f7f8f2', fontSize: 14, fontWeight: '700' }, arrow: { fontSize: 23 },
  lowerGrid: { flexDirection: 'row', gap: 12 }, lowerGridMobile: { flexDirection: 'column' }, workload: { flex: 1.7, padding: 20 }, activity: { flex: 1, padding: 20 }, sectionTitle: { color: '#f7f8f2', fontSize: 28, fontWeight: '900' }, sectionSubtitle: { color: '#d0d9d3', fontSize: 15, marginTop: 3 }, tableHeader: { borderBottomColor: 'rgba(225,255,235,.28)', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 22, paddingBottom: 10 }, tableHeaderText: { color: '#d4ddd7', fontSize: 11 }, analystRow: { alignItems: 'center', borderBottomColor: 'rgba(225,255,235,.22)', borderBottomWidth: 1, flexDirection: 'row', gap: 12, minHeight: 76 }, analystIdentity: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 12 }, initials: { alignItems: 'center', borderColor: '#6fffc0', borderRadius: 28, borderWidth: 1.5, height: 48, justifyContent: 'center', width: 48 }, initialsText: { color: '#f7f8f2', fontSize: 17, fontWeight: '800' }, analystName: { color: '#f7f8f2', fontSize: 16, fontWeight: '800' }, workloadCount: { color: '#f7f8f2', flex: 1, fontSize: 15 }, smallButton: { alignItems: 'center', borderColor: '#64efb4', borderRadius: 9, borderWidth: 1, justifyContent: 'center', minHeight: 44, minWidth: 116, paddingHorizontal: 12 }, smallButtonText: { color: '#f7f8f2', fontWeight: '700' }, activityRow: { alignItems: 'center', borderTopColor: 'rgba(225,255,235,.22)', borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', minHeight: 92, paddingVertical: 14 }, activityLabel: { color: '#f7f8f2', fontSize: 16, fontWeight: '900' }, activityDetail: { color: '#c5d0c9', fontSize: 13, lineHeight: 18, marginTop: 5, maxWidth: 270 }, activityArrow: { color: '#d6ff19', fontSize: 29 },
  state: { alignItems: 'center', justifyContent: 'center', minHeight: 300, padding: 28 }, stateCopy: { color: '#f7f8f2', fontSize: 18, textAlign: 'center' }, retry: { alignItems: 'center', backgroundColor: '#d6ff19', borderRadius: 9, justifyContent: 'center', marginTop: 18, minHeight: 48, minWidth: 130 }, retryText: { color: '#07110d', fontWeight: '900' },
});
