import 'reflect-metadata';
import 'dotenv/config';

process.env.NODE_ENV ??= 'test';
process.env.PORT ??= '3000';
process.env.DATABASE_URL ??= 'postgresql://test:test@127.0.0.1:5433/new_talents_test';
process.env.ALLOWED_ORIGINS ??= 'http://localhost:8081';
process.env.JWT_ISSUER ??= 'new-talents.test';
process.env.JWT_AUDIENCE ??= 'new-talents-client';
process.env.JWT_SIGNING_SECRET ??= 'test-signing-secret-that-is-long-enough-to-be-safe';
process.env.AUTH_ACCESS_TOKEN_TTL_SECONDS ??= '900';
process.env.AUTH_REFRESH_TOKEN_TTL_SECONDS ??= '2592000';
process.env.AUTH_TEMPORARY_CREDENTIAL_TTL_SECONDS ??= '86400';
process.env.AUTH_ATTEMPT_LIMIT ??= '5';
process.env.AUTH_ATTEMPT_WINDOW_SECONDS ??= '900';
process.env.AUTH_TRUSTED_PROXY ??= 'false';
process.env.AUTH_SESSION_RETENTION_DAYS ??= '90';
process.env.AUTH_ATTEMPT_RETENTION_HOURS ??= '24';
process.env.PASSPORT_DOCUMENT_HMAC_KEY ??= 'AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=';
process.env.PASSPORT_NAME_DOB_HMAC_KEY ??= 'AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=';
process.env.PASSPORT_PRIVATE_ENCRYPTION_KEY ??= 'AwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM=';
