export const permissionCatalog = Object.freeze({
  'foundation.internal.evaluate': Object.freeze({ roles: ['ADMINISTRATOR', 'ANALYST'] as const, academy: false, tutor: false, anonymous: false }),
  'foundation.tutor.related-resource': Object.freeze({ roles: ['TUTOR'] as const, academy: false, tutor: true, anonymous: false }),
  'foundation.academy.scoped-resource': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false }),
  'foundation.public.read': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: true }),
  'foundation.privileged.role-change': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false }),
  'foundation.privileged.membership-change': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false }),
  'passport.tutor.create': Object.freeze({ roles: ['TUTOR'] as const, academy: false, tutor: false, anonymous: false }),
  'passport.particular.create': Object.freeze({ roles: ['USER'] as const, academy: false, tutor: false, particular: true, anonymous: false }),
  'passport.particular.manage': Object.freeze({ roles: ['USER'] as const, academy: false, tutor: false, particular: true, anonymous: false }),
  'passport.academy.create': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false }),
  'passport.tutor.manage': Object.freeze({ roles: ['TUTOR'] as const, academy: false, tutor: true, anonymous: false }),
  'passport.academy.manage': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false }),
  'passport.review': Object.freeze({ roles: ['ANALYST'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'analyst-current-custody' as const }),
  'passport.activate': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false }),
  'passport.history.tutor': Object.freeze({ roles: ['TUTOR'] as const, academy: false, tutor: true, anonymous: false }),
  'passport.history.particular': Object.freeze({ roles: ['USER'] as const, academy: false, tutor: false, particular: true, anonymous: false }),
  'passport.history.academy': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false }),
  'passport.history.internal': Object.freeze({ roles: ['ANALYST', 'ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'administrator-or-analyst-custody' as const }),
  'registration.request.create.personal-adult': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: true, registrationPolicy: 'public-create' as const }),
  'registration.request.create.represented-minor': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: true, registrationPolicy: 'public-create' as const }),
  'registration.request.create.formal-academy': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: true, registrationPolicy: 'public-create' as const }),
  'registration.request.create.natural-person-academy': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: true, registrationPolicy: 'public-create' as const }),
  'registration.request.own.view': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-view' as const }),
  'registration.request.own.edit-draft': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-draft' as const }),
  'registration.request.own.submit': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-submit' as const }),
  'registration.request.own.correct': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-correction' as const }),
  'registration.request.own.resubmit': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-resubmit' as const }),
  'registration.request.own.upload-evidence': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-editable' as const }),
  'registration.request.own.view-deletion-status': Object.freeze({ roles: [] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'own-view' as const }),
  'registration.request.academy.list': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false, registrationPolicy: 'academy-view' as const }),
  'registration.request.academy.view': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false, registrationPolicy: 'academy-view' as const }),
  'registration.request.academy.create-additional-account': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false, registrationPolicy: 'academy-responsible-create' as const }),
  'registration.request.academy.create-adult-player': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false, registrationPolicy: 'academy-create' as const }),
  'registration.request.academy.create-minor-player': Object.freeze({ roles: ['ACADEMY_USER'] as const, academy: true, tutor: false, anonymous: false, registrationPolicy: 'academy-create' as const }),
  'registration.review.list': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-view' as const }),
  'registration.review.view': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-view' as const }),
  'registration.review.view-evidence': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-evidence' as const }),
  'registration.review.request-correction': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-submitted' as const }),
  'registration.review.confirm-dossier': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-dossier' as const }),
  'registration.review.approve': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-approve' as const }),
  'registration.review.reject': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-submitted' as const }),
  'registration.review.view-deletion-status': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-view' as const }),
  'registration.review.retry-deletion': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-retry-deletion' as const }),
  'registration.review.progress': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-progress' as const }),
  'registration.dossier.list': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-dossier-list' as const }),
  'registration.dossier.view': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, registrationPolicy: 'admin-dossier-view' as const }),
  'passport.custody.list': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'admin-custody-list' as const }),
  'passport.custody.view': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'admin-custody-view' as const }),
  'passport.custody.list-analysts': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'admin-custody-list-analysts' as const }),
  'passport.custody.assign': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'admin-custody-assign' as const }),
  'passport.custody.change': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'admin-custody-change' as const }),
  'passport.custody.remove': Object.freeze({ roles: ['ADMINISTRATOR'] as const, academy: false, tutor: false, anonymous: false, resourcePolicy: 'admin-custody-remove' as const }),
});
export type Permission = keyof typeof permissionCatalog;
export const isPermission = (value: unknown): value is Permission => typeof value === 'string' && value in permissionCatalog;
