import { Body, Controller, HttpCode, Post, Req, Res, UseGuards } from '@nestjs/common';
import { AuthenticationService } from './authentication.service.js';
import { RefreshTokenService } from './refresh-token.service.js';
import { SessionService } from './session.service.js';
import { TemporaryCredentialService } from './temporary-credential.service.js';
import { CredentialReplacementService } from './credential-replacement.service.js';
type Response = { setHeader(name: string, value: string): Response; status(code: number): Response };
import { PublicRoute } from './public-route.decorator.js';
import { AuthenticationGuard, type RequestActor } from './authentication.guard.js';

@Controller('auth') @UseGuards(AuthenticationGuard)
export class AuthenticationController {
  constructor(private readonly loginService: AuthenticationService, private readonly refreshes: RefreshTokenService, private readonly sessions: SessionService, private readonly temporary: TemporaryCredentialService, private readonly replacements: CredentialReplacementService) {}
  @Post('login') @PublicRoute() async login(@Body() body: { email?: unknown; password?: unknown }, @Req() request: { socket?: { remoteAddress?: string } }, @Res({ passthrough: true }) response: Response) { const result = await this.loginService.login({ email: body.email, password: body.password, source: { remoteAddress: request.socket?.remoteAddress } }); if (result.outcome === 'authenticated') { response.setHeader('Cache-Control', 'no-store'); return { accessToken: result.accessToken, refreshToken: result.refreshToken, tokenType: 'Bearer', expiresIn: 900 }; } response.status(result.outcome === 'throttled' ? 429 : 401); return { error: result.outcome === 'throttled' ? 'throttled' : 'authentication_failed' }; }
  @Post('refresh') @PublicRoute() async refresh(@Body() body: { refreshToken?: unknown }, @Res({ passthrough: true }) response: Response) { const result = await this.refreshes.rotate(body.refreshToken); if (result.outcome === 'rotated') { response.setHeader('Cache-Control', 'no-store'); return { refreshToken: result.refreshToken }; } response.status(401); return { error: 'authentication_failed' }; }
  @Post('initial-credential/replace') @PublicRoute() async replace(@Body() body: { identityId?: unknown; temporaryCredential?: unknown; newPassword?: unknown }, @Res({ passthrough: true }) response: Response) { const result = await this.replacements.replace({ identityId: body.identityId, temporaryCredential: body.temporaryCredential, replacementPassword: body.newPassword }); if (result.outcome === 'replaced') { response.status(500); return { error: 'internal_error' }; } response.status(401); return { error: 'authentication_failed' }; }
  @Post('logout') @HttpCode(204) async logout(@Req() request: { actor: RequestActor }) { await this.sessions.logoutCurrent(request.actor.identityId, request.actor.sessionId); }
  @Post('logout-all') @HttpCode(204) async logoutAll(@Req() request: { actor: RequestActor }) { await this.sessions.logoutAll(request.actor.identityId); }
  @Post('credentials/provision') async provision(@Body() body: { identityId?: unknown }, @Req() request: { actor: RequestActor }, @Res({ passthrough: true }) response: Response) { const result = await this.temporary.provision({ actorIdentityId: request.actor.identityId, identityId: body.identityId, normalizedEmail: `pending-${body.identityId}@invalid.local` }); if (result.outcome === 'provisioned') { response.status(201).setHeader('Cache-Control','no-store'); return { temporaryCredential: result.temporaryCredential, expiresIn: 86400 }; } response.status(403); return { error: 'forbidden' }; }
  @Post('credentials/reissue') async reissue(@Body() body: { identityId?: unknown }, @Req() request: { actor: RequestActor }, @Res({ passthrough: true }) response: Response) { const result = await this.temporary.reissue({ actorIdentityId: request.actor.identityId, identityId: body.identityId, normalizedEmail: `pending-${body.identityId}@invalid.local` }); if (result.outcome === 'provisioned') { response.status(201).setHeader('Cache-Control','no-store'); return { temporaryCredential: result.temporaryCredential, expiresIn: 86400 }; } response.status(403); return { error: 'forbidden' }; }
}
